version: "3"
services:
  # python-server:
  #   build:
  #     context: ./python-server/
  #     dockerfile: ./Dockerfile
  #     args:
  #       - DB_HOST=db:3306
  #       - DB_USERNAME=user
  #       - DB_PASSWORD=passw0rd
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     WAIT_HOSTS: db:3306
  #   command: sh -c "python ./manage.py db upgrade && python ./manage.py db migrate"
  #   depends_on:
  #     - db
  # vue-frontend:
  #   build:
  #     context: ./vue-frontend/
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "8081:8081"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'passw0rd'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'passw0rd'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3307 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - similarity-db:/var/lib/mysql
# Names our volume
volumes:
  similarity-db:
     
